#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring the NGINX web server configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_systemctl --service="nginx" --action="reload"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
rm $install_dir/gunicorn.pid

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

myynh_fix_file_permissions

#=================================================
# PYTHON VIRTUALENV
# Maybe the backup contains a other Python version
#=================================================
ynh_script_progression "Create and setup Python virtualenv..."

myynh_setup_python_venv

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring the systemd $app configuration..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet
ynh_systemctl --service=$app --action="start" --log_path="$log_file"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="Gunicorn running a FastAPI app" --log="/var/log/$app/$app.log"

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Setup logging..."

myynh_setup_log_file
ynh_restore "/etc/logrotate.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
