#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring systemd service '$app'..."

ynh_config_add_systemd

#=================================================
# PYTHON VIRTUALENV
#=================================================
ynh_script_progression "Create and setup Python virtualenv..."

ynh_config_add --template="requirements.txt" --destination="$install_dir/requirements.txt"

myynh_setup_python_venv

#=================================================
# copy config files
# ================================================
ynh_script_progression "Create $app configuration files..."

ynh_config_add --template="gunicorn.conf.py" --destination="$install_dir/gunicorn.conf.py"

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Upgrading logrotate configuration..."

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate "$log_file"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Set file permissions..."

myynh_fix_file_permissions

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Gunicorn running a FastAPI app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
